version: "3.8"
services:

  database:
   image: 'mcr.microsoft.com/mssql/server:2022-latest'
   environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Zaq12wsx
   volumes:
      - /IO-PROJ-DATA/database/:/var/opt/mssql/
   ports:
    - 1433:1433

  backend:
    build: ./Backend
    environment:
     - DATABASE_IP=<your-ip-address>
    ports:
      - 8080:8080
    volumes:
      - /IO-PROJ-DATA/backend/zdjecia:/app/zdjecia
    restart: always
    depends_on:
      - database

  frontend:
    build:
     context: ./Frontend/web/Album/album/
     args:
      DOCKER_ENV_FRONT_URL: "{URL}" # default http://<your-ip-address>:8080/api
    ports:
      - 3001:3000
    restart: always
    depends_on:
      - backend