services:

  database:
   image: 'mcr.microsoft.com/mssql/server:2022-latest'
   environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Zaq12wsx
   volumes:
      - /docker_github/data/database/:/var/opt/mssql/
   ports:
    - 1433:1433

  backend:
    build: ./Backend
    environment:
     - DATABASE_IP=<your-ip-address>
     - ConnectionStrings__DbConnection=Server=<your-ip-address>,1433;Database=ProjectIO;User Id=sa;Password=Zaq12wsx;Encrypt=True;TrustServerCertificate=True;
     - BaseBackendUrl=http://<your-ip-address>:8080 # If it's production ready, change to domain name

    ports:
      - 8080:8080
    volumes:
      - /docker_github/data/backend/zdjecia:/app/zdjecia
    restart: always
    depends_on:
      - database

  frontend:
    build:
     context: ./Frontend/web/Album/album/
     args:
      DOCKER_ENV_FRONT_URL: "{URL}" # default http://<your-ip-address>:8080/api
    ports:
      - 3001:3000
    restart: always
    depends_on:
      - backend
